// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQqHEkwJKrlQ87GwX0wcGsO5Dg9Yz86fs',
    appId: '1:714070160301:web:a2d64b178fc825ea85e724',
    messagingSenderId: '714070160301',
    projectId: 'stage-db-2c0b5',
    authDomain: 'stage-db-2c0b5.firebaseapp.com',
    storageBucket: 'stage-db-2c0b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl5rRQyM9uqYsjOtLGr4hEwpjRW7zM5ac',
    appId: '1:714070160301:android:f015ffb27f9e646e85e724',
    messagingSenderId: '714070160301',
    projectId: 'stage-db-2c0b5',
    storageBucket: 'stage-db-2c0b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ6kSo-_GwpOE0t-9NjjyMwNyN6i4h-wM',
    appId: '1:714070160301:ios:919ea49a6623d6a985e724',
    messagingSenderId: '714070160301',
    projectId: 'stage-db-2c0b5',
    storageBucket: 'stage-db-2c0b5.appspot.com',
    iosBundleId: 'com.example.stageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ6kSo-_GwpOE0t-9NjjyMwNyN6i4h-wM',
    appId: '1:714070160301:ios:919ea49a6623d6a985e724',
    messagingSenderId: '714070160301',
    projectId: 'stage-db-2c0b5',
    storageBucket: 'stage-db-2c0b5.appspot.com',
    iosBundleId: 'com.example.stageApp',
  );
}
